name: Deploy Mini App and Parse Horoscope

on:
  push:
    branches:
      - main
  
jobs:
  parse-horoscope:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          cd parser
          pip install -r requirements.txt

      - name: Parse horoscope
        run: |
          cd parser
          python parse_horoscope.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add parser/horoscope.json
          git commit -m "Update horoscope data"
          git push

  deploy:
    runs-on: ubuntu-latest
    needs: parse-horoscope
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
          keep_files: true